languageCode:           "en"
title:                  "Admin Dashboard"
# baseURL:              "http://localhost:1313"
baseURL:                "https://nextcloud-three.vercel.app//"
enableInlineShortcodes: true
canonifyURLs: true

params:
  homepage: "https://nextai.co.in/"
  authors: 
  social_image_path: images/

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
    style:              colorful
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"
